# Variables
@baseUrl = http://localhost:3333

# @name healthCheck
GET {{baseUrl}}/health

###

# @name getRooms
GET {{baseUrl}}/rooms

###

# @name createRooms
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "name": "Sala de teste"
}

###

@roomId = {{createRooms.response.body.$.roomId}}

###

# @name getQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions

###

# @name createQuestions
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "O que é o React?"
}